const APP_ICONS = [
  {
    id: 'default',
    label: '知乎蓝',
    color: '#0084ff',
    iosName: null,
    androidAlias: 'AppIconDefaultAlias',
  },
  {
    id: 'indigo',
    label: '极客靛',
    color: '#6366f1',
    iosName: 'ZhihuIconIndigo',
    androidAlias: 'AppIconIndigoAlias',
  },
  {
    id: 'mint',
    label: '薄荷青',
    color: '#00a896',
    iosName: 'ZhihuIconMint',
    androidAlias: 'AppIconMintAlias',
  },
  {
    id: 'emerald',
    label: '翡翠绿',
    color: '#10b981',
    iosName: 'ZhihuIconEmerald',
    androidAlias: 'AppIconEmeraldAlias',
  },
  {
    id: 'sunset',
    label: '落日橙',
    color: '#f97316',
    iosName: 'ZhihuIconSunset',
    androidAlias: 'AppIconSunsetAlias',
  },
  {
    id: 'sakura',
    label: '樱花粉',
    color: '#ec4899',
    iosName: 'ZhihuIconSakura',
    androidAlias: 'AppIconSakuraAlias',
  },
  {
    id: 'peach',
    label: '蜜桃粉',
    color: '#ff758f',
    iosName: 'ZhihuIconPeach',
    androidAlias: 'AppIconPeachAlias',
  },
  {
    id: 'rose',
    label: '玫瑰红',
    color: '#f43f5e',
    iosName: 'ZhihuIconRose',
    androidAlias: 'AppIconRoseAlias',
  },
  {
    id: 'violet',
    label: '紫罗兰',
    color: '#8b5cf6',
    iosName: 'ZhihuIconViolet',
    androidAlias: 'AppIconVioletAlias',
  },
  {
    id: 'slate',
    label: '静谧灰',
    color: '#64748b',
    iosName: 'ZhihuIconSlate',
    androidAlias: 'AppIconSlateAlias',
  },
  {
    id: 'aurora',
    label: '极光',
    color: '#6366f1',
    gradient: {
      start: [0, 0],
      end: [1, 1],
      colors: ['#22d3ee', '#6366f1', '#ec4899'],
    },
    iosName: 'ZhihuIconAurora',
    androidAlias: 'AppIconAuroraAlias',
  },
  {
    id: 'rainbow',
    label: '彩虹',
    color: '#f97316',
    bands: {
      start: [0, 0],
      end: [1, 0],
      colors: [
        '#5ebd3e',
        '#ffb900',
        '#f78200',
        '#e23838',
        '#973999',
        '#009cdf',
      ],
    },
    iosName: 'ZhihuIconRainbow',
    androidAlias: 'AppIconRainbowAlias',
  },
];

module.exports = { APP_ICONS };
