jest.mock('@expo/config-plugins', () => ({
  withAppBuildGradle: (config, action) => action(config),
}));

const withAndroidAbiSplits = require('../plugins/withAndroidAbiSplits');

function apply(contents, language = 'groovy') {
  return withAndroidAbiSplits({ modResults: { contents, language } }).modResults
    .contents;
}

describe('Android ABI split config plugin', () => {
  const before = '// existing configuration\nandroid {\n';
  const after = '    defaultConfig { minSdkVersion 24 }\n}\n// preserve this\n';

  test('a repeated prebuild produces one unchanged owned block', () => {
    const first = apply(before + after);
    expect(apply(first)).toBe(first);
    expect(first.split('// @generated by withAndroidAbiSplits')).toHaveLength(
      2,
    );
    expect(first.startsWith(before)).toBe(true);
    expect(first.endsWith(after)).toBe(true);
  });

  test('a normal prebuild upgrades the old fixed four-ABI block', () => {
    const oldBlock = `    // @generated by withAndroidAbiSplits
    splits {
        abi {
            reset()
            enable true
            universalApk false
            include "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
    }
`;
    const result = apply(before + oldBlock + after);
    expect(result).toBe(apply(before + after));
    expect(result).toContain(
      'project.findProperty("reactNativeArchitectures")',
    );
    expect(result).toContain('include(*splitAbis.unique())');
  });

  test('preserves surrounding Windows line endings and whitespace', () => {
    const windowsBefore = before.replaceAll('\n', '\r\n');
    const windowsAfter = after.replaceAll('\n', '\r\n');
    const first = apply(windowsBefore + windowsAfter);
    expect(first.startsWith(windowsBefore)).toBe(true);
    expect(first.endsWith(windowsAfter)).toBe(true);
    expect(apply(first)).toBe(first);
  });

  test('preserves unmarked surrounding blocks including braces in comments and strings', () => {
    const extra = `    packagingOptions { resources { excludes += ["{unchanged}"] } }
`;
    const oldBlock = `    // @generated by withAndroidAbiSplits
    splits {
        // } this brace does not close the block
        abi { /* } */ include "}" }
    }
`;
    const currentBlock = apply(before + after).slice(
      before.length,
      -after.length,
    );
    expect(apply(before + extra + oldBlock + after)).toBe(
      before + extra + currentBlock + after,
    );
  });

  test('refuses damaged or ambiguous markers instead of deleting surrounding code', () => {
    const marker = '    // @generated by withAndroidAbiSplits\n';
    expect(() => apply(before + marker + after)).toThrow('marked');
    expect(() => apply(`${before}${marker}splits {\n`)).toThrow('incomplete');
    expect(() => apply(before + marker + marker + after)).toThrow('multiple');
    expect(() =>
      apply('android { // @generated by withAndroidAbiSplits\n'),
    ).toThrow('own line');
  });

  test('refuses unsupported native project formats', () => {
    expect(() => apply(before + after, 'kotlin')).toThrow('Groovy');
    expect(() => apply('dependencies {}')).toThrow('Android block');
  });
});
