const { withAppBuildGradle } = require('@expo/config-plugins');

const SPLITS_MARKER = '// @generated by withAndroidAbiSplits';
const SPLITS_CONFIG = `    ${SPLITS_MARKER}
    splits {
        abi {
            def supportedAbis = ["armeabi-v7a", "arm64-v8a", "x86", "x86_64"]
            def requestedAbis = project.findProperty("reactNativeArchitectures")
            def splitAbis = requestedAbis == null ? supportedAbis : requestedAbis.toString().split(",", -1).collect { it.trim() }
            if (splitAbis.any { it.isEmpty() || !supportedAbis.contains(it) }) {
                throw new GradleException("reactNativeArchitectures must contain supported, nonempty Android ABIs")
            }
            reset()
            enable true
            universalApk false
            include(*splitAbis.unique())
        }
    }
`;

// Replace only the block owned by this plugin. Its former version returned as
// soon as it found the marker, preventing a normal prebuild from applying fixes.
function findGeneratedBlock(contents) {
  const marker = contents.indexOf(SPLITS_MARKER);
  if (marker < 0) return null;
  if (contents.indexOf(SPLITS_MARKER, marker + SPLITS_MARKER.length) >= 0) {
    throw new Error('Found multiple Android ABI split plugin markers.');
  }
  const lineStart = contents.lastIndexOf('\n', marker - 1) + 1;
  if (contents.slice(lineStart, marker).trim()) {
    throw new Error('Android ABI split plugin marker must be on its own line.');
  }
  const header = contents
    .slice(marker + SPLITS_MARKER.length)
    .match(/^\s*splits\s*\{/);
  if (!header)
    throw new Error('Could not find the marked Android ABI split block.');
  const open = marker + SPLITS_MARKER.length + header[0].length - 1;
  let depth = 0;
  let quote = null;
  let escaped = false;
  let lineComment = false;
  let blockComment = false;
  for (let index = open; index < contents.length; index += 1) {
    const character = contents[index];
    const next = contents[index + 1];
    if (lineComment) {
      if (character === '\n') lineComment = false;
      continue;
    }
    if (blockComment) {
      if (character === '*' && next === '/') {
        blockComment = false;
        index += 1;
      }
      continue;
    }
    if (quote) {
      if (escaped) escaped = false;
      else if (character === '\\') escaped = true;
      else if (character === quote) quote = null;
      continue;
    }
    if (character === '/' && next === '/') {
      lineComment = true;
      index += 1;
    } else if (character === '/' && next === '*') {
      blockComment = true;
      index += 1;
    } else if (character === '"' || character === "'") {
      quote = character;
    } else if (character === '{') {
      depth += 1;
    } else if (character === '}') {
      depth -= 1;
      if (depth === 0) {
        const newline = contents.slice(index + 1).match(/^[ \t]*\r?\n/);
        return {
          start: lineStart,
          end: index + 1 + (newline?.[0].length ?? 0),
        };
      }
    }
  }
  throw new Error('The marked Android ABI split block is incomplete.');
}

module.exports = function withAndroidAbiSplits(config) {
  return withAppBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== 'groovy') {
      throw new Error('Android ABI splits require a Groovy app build.gradle.');
    }

    const generatedBlock = findGeneratedBlock(gradleConfig.modResults.contents);
    if (generatedBlock) {
      const contents = gradleConfig.modResults.contents;
      gradleConfig.modResults.contents = `${contents.slice(0, generatedBlock.start)}${SPLITS_CONFIG}${contents.slice(generatedBlock.end)}`;
      return gradleConfig;
    }

    const androidBlock = /(android\s*\{)([ \t]*\r?\n)?/;
    if (!androidBlock.test(gradleConfig.modResults.contents)) {
      throw new Error('Could not find the Android block in app/build.gradle.');
    }

    gradleConfig.modResults.contents = gradleConfig.modResults.contents.replace(
      androidBlock,
      (_match, opening, newline) =>
        `${opening}${newline ?? '\n'}${SPLITS_CONFIG}`,
    );
    return gradleConfig;
  });
};
