const { withAppBuildGradle } = require('@expo/config-plugins');

const SPLITS_MARKER = '// @generated by withAndroidAbiSplits';
const SPLITS_CONFIG = `${SPLITS_MARKER}
    splits {
        abi {
            reset()
            enable true
            universalApk false
            include "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
    }
`;

module.exports = function withAndroidAbiSplits(config) {
  return withAppBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== 'groovy') {
      throw new Error('Android ABI splits require a Groovy app build.gradle.');
    }

    if (gradleConfig.modResults.contents.includes(SPLITS_MARKER)) {
      return gradleConfig;
    }

    const androidBlock = /android\s*\{/;
    if (!androidBlock.test(gradleConfig.modResults.contents)) {
      throw new Error('Could not find the Android block in app/build.gradle.');
    }

    gradleConfig.modResults.contents = gradleConfig.modResults.contents.replace(
      androidBlock,
      (match) => `${match}\n    ${SPLITS_CONFIG}`,
    );
    return gradleConfig;
  });
};
